---
title: "Toxoplasma"
author: "Nallely Borbolla"
date: "5 de junio de 2019"
output:
  html_document: default
  pdf_document: default
  word_document: default
---

```{r}
#direccion="C:/Users/xavy28/Dropbox/TESIS/ProgramasR/Toxoplasma/"
direccion="~/Dropbox/TesisNallelyCB/ProgramasR/Toxoplasma/"
```

## Ecuaciones propuestas para Toxoplasma 

$$\dot{H_0}=\phi -\beta_P H_0P-\epsilon_P H_0-\mu_0H_0$$
  $$\dot{P_1}=\epsilon_PH_0+\beta_P H_0P-\iota_1P_1$$
  $$\dot{P_2}=\psi\iota_1P_1-\iota_2P_2$$
  $$\dot{P_3}=\iota_2P_2-\gamma P_3$$
  $$\dot{T}=\gamma P_3 N_P-\beta_P H_0P-\mu_P P$$
 
`````{r}
library(deSolve)
```
Definimos la funcion

```{r}
Toxoplasma <- function(t, state, parameters) {
  with(as.list(c(state, parameters)), {
    dho <- phi-beta*ho*P-mo*ho-epsilon*ho
    dP1 <- epsilon*ho+beta*ho*P-iota1*P1
    dP2 <- psi*iota1*P1-iota2*P2
    dP3 <- iota2*P2-gama*P3
    dP <- gama*NP*P3-beta*ho*P-mP*P
    list(c(dho,dP1,dP2,dP3,dP))
  })
}
```


```{r}
parameters <- c(beta =0.02, phi= 10, iota1 = 1/1.5, iota2 =1/6, gama=1/42,psi = 0.85, mo=1/48,mP=1/6, epsilon=60, rp=1/8, NP=64)
state <- c(ho = 3000, P1 = 0, P2 = 0,P3=0, P= 1)
times <- seq(0,350, by = 1)
out <- ode(y = state, times = times, func = Toxoplasma, parms = parameters)
```

> Para los parametros consideramos:


*La asociación con el con el centrosoma/ adquisición de nutrientes. Se considera con un 85% que es lo reportado experimentalmente.(Isabell Coppens & Julia D. Romano)

```{r}
#pdf(paste0(direccion, "Grafica.Resultado.ToxoplasmaF.pdf"))
plot(out,col="blue")
plot(out[,"P"],pch = ".")
dev.off()
```


```{r}
plot(out,col="blue")
plot(out[,"P"],out[,"ho"],pch = ".")
```


```{r}
tail(out,n=50)
```
